version: "{build}"
skip_tags: true
clone_folder: c:\gogs.io\gogs
clone_depth: 1

environment:
  GO111MODULE: on
  GOPROXY: "https://proxy.golang.org,direct"

stack: go 1.13

build: false
deploy: false

install:
  - go version
  - go env
  - go build -v
